<p>
Here are some of the fundamental tools our technicians use to remedy your computer's woes.
</p>
<h2>Internet Browsing and Protection</h2>
<ul>
<li><a href="http://www.mozilla.org/products/firefox/" target="_blank">Mozilla Firefox</a><font color="green">*</font></li>
<li><a href="http://www.mozilla.org/products/mozilla1.x/" target="_blank">Mozilla Suite</a><font color="green">*</font></li>
</ul>
<h2>Spyware and Adware Removal</h2>
<ul>
<li><a href="http://www.pctools.com/spyware-doctor/" target="_blank">Spyware Doctor</a><font color="green">*</font></li>
<li><a href="http://www.safer-networking.org/en/index.html" target="_blank">Spybot - Search and Destroy</a><font color="green">*</font></li>
<li><a href="http://www.lavasoftusa.com/software/adaware/" target="_blank">Ad-Aware</a><font color="green">*</font></li>
<li><a href="http://www.sunbelt-software.com/CounterSpy.cfm" target="_blank">CounterSpy</a><font color="blue">*</font></li>
<li><a href="http://www.noadware.net/?hop=wintech1" target="_blank">NoAdware</a></li>
</ul>
<h2>Virus Awareness and Removal</h2>
<ul>
<li><a href="http://www.symantecstore.com/dr/sat2/ec_MAIN.Entry16?PN=1&SP=10023&S1=&S2=&S3=&S4=&S5=&V1=648682&V2=&V3=&V4=&V5=11031981&xid=49997&DSP=0&CUR=840&PGRP=0&CACHE_ID=0" target="_blank">Norton Antivirus</a><font color="blue">*</font></li>
<li><a href="http://www.digitalriver.com/dr/v2/ec_MAIN.Entry10?xid=16269&SP=10023&PN=1&V1=661822&DSP=&CUR=840&PGRP=0&CACHE_ID=0" target="_blank">PC-cillin Internet Security</a></li>
<li><a href="http://www.grisoft.com/doc/1" target="_blank">AVG Antivirus</a><font color="green">*</font></li>
</ul>
<br>
<font color="green">*</font>Free utility.<br>
<font color="blue">*</font>Free trial.