<body background="imgs/bg.png">

<div id="main">
<img style="position:absolute;z-index:1;left:0;top:0;" src="imgs/logo.png" height="91" width="150">
<img src="imgs/crn_tl.png" style="position:absolute;z-index:4;left:143;top:0;">

<div style="position:absolute;z-index:6;left:17;top:120;">

<table cellpadding=0 cellspacing=0 border=0 style="width:120px;">
<tr><td class="button"  onMouseOver="this.style.background='url(imgs/button2.png)'" onMouseOut="this.style.background='url(imgs/button1.png)'">
<img src="imgs/line.gif" hspace=0 vspace=0 height=0 width=120><br>
<a href="home.php" style="position:absolute;left:0;top:10;width:120;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Home</b></a>
</td></tr>
<tr><td class="button"  onMouseOver="this.style.background='url(imgs/button2.png)'" onMouseOut="this.style.background='url(imgs/button1.png)'">
<img src="imgs/line.gif" hspace=0 vspace=0 height=0 width=120><br>
<a href="services.php" style="position:absolute;left:0;top:47;width:120;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Services</b></a>
</td></tr>
<tr><td class="button"  onMouseOver="this.style.background='url(imgs/button2.png)'" onMouseOut="this.style.background='url(imgs/button1.png)'">
<img src="imgs/line.gif" hspace=0 vspace=0 height=0 width=120><br>
<a href="utilities.php" style="position:absolute;left:0;top:84;width:120;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Utilities</b></a>
</td></tr>
<tr><td class="button"  onMouseOver="this.style.background='url(imgs/button2.png)'" onMouseOut="this.style.background='url(imgs/button1.png)'">
<img src="imgs/line.gif" hspace=0 vspace=0 height=0 width=120><br>
<a href="contact.php" style="position:absolute;left:0;top:121;width:120;">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<b>Contact</b></a>
</td></tr>
</table>

<img src="imgs/aplus.gif" style="position:absolute;top:155;left:25;">
</div>
