<html>
<head>
<title>
Phoenix Tech Computer Repair
</title>
<style type="text/css">
body,tr,td,p,li {font-family: tahoma; color: #ffffff; font-size: 10pt; background: url('imgs/bg_main.png');}

a {color: #ffffff; text-decoration: underline;}
a:link { color: #ffffff; text-decoration: underline;}
a:visited { color: #ffffff; text-decoration: underline;}
a:active { color: #ffffff; text-decoration: underline;}
a:hover { color: #ffffff; text-decoration: underline;}

.head { font-type:arial;color: #FFDD00;font-style: none;font-size:14pt;}
</style>
<script src="http://thinkphoenixtech.com/src/support.js" type='text/javascript'></script>
</head>
<body>